spring:
  liquibase:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
  application.name: java-spring
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: service
    password: service
